name: transformer
channels:
- pytorch
- defaults
- peterjc123
dependencies:
- scipy
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pip
- scipy
- pytorch
- tqdm
- pip:
  - nltk
  - subword-nmt
  - tensorboardX==1.5